### ISSUE TITLE
如何使用它？能否出个新手教程谢谢

### ISSUE THREAD

**Issue by lonbaw** [dj940212/vue-blog#2]

**Comment by dj940212** [comment]
如果你想看代码，克隆下来配置一个secretData.js文件，npm run dev就可以跑起来。如果你想用作自己的博客，那么你需要一个服务器，然后部署在上面

**Comment by phpxi** [comment]
我这边想在本地登录,死活登录不上。怎么解决?

**Comment by 120448999** [comment]
单纯配置个 mongo 的数据库。 但是没有数据表结构和。后端代码。实在那他没有办法
