### ISSUE TITLE
缺少对象800A138F

### ISSUE THREAD

**Issue by atange** [dj940212/vue-blog#4]
启动的时候 类似的错误 https://blog.csdn.net/dexing07/article/details/53322409

**Comment by atange** [comment]
![20180414190921](https://user-images.githubusercontent.com/12076578/38767628-5f926fa8-4017-11e8-9bb1-63e92f80c012.png)
![20180414190957](https://user-images.githubusercontent.com/12076578/38767632-7855cc06-4017-11e8-9286-bf0117b09724.png)

**Comment by dj940212** [comment]
@sonong 运行项目的命令式`npm run dev` , 配置文件文档有误,应该添加在`~/server/config/index.js`

**Comment by atange** [comment]
C:\GitHub\last-blog\server\config\index.js 
27017后面de数据库是随便给吗？
export default {
	db: 'mongodb://username:password@localhost:27017/admin',
	user: {
        username: 'infodba',
        password: '1234'
    }
}
启动
![authentication](https://user-images.githubusercontent.com/12076578/39093159-7b88bb86-464d-11e8-94ac-48f2e1e55635.png)

**Comment by atange** [comment]
今天尝试export default {
	db: 'mongodb://infodba:1234@localhost:27017/admin',
}
就成功了
![success](https://user-images.githubusercontent.com/12076578/39093461-99d25890-4652-11e8-81bb-007ad574bf59.png)

**Comment by alexzhao8326** [comment]
@dj940212 没有在server文件夹下发现config文件夹

**Comment by atange** [comment]
@alexzhao8326 自己创建。
![20180427215139](https://user-images.githubusercontent.com/12076578/39366266-00a11cc0-4a66-11e8-9a11-b693ee0f9b7a.png)

目前 run dev  可以启动  但是登陆不上去。初步估计windows  install err 问题
